# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: inbox

builds:
  - id: inbox
    main: .
    binary: inbox
    env:
      - CGO_ENABLED=0
      - GOEXPERIMENT=jsonv2
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X go.withmatt.com/inbox/cmd.version={{.Version}}

archives:
  - id: default
    ids:
      - inbox
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    formats:
      - tar.gz

checksum:
  name_template: 'checksums.txt'

homebrew_casks:
  - name: inbox
    homepage: https://github.com/mattrobenolt/inbox
    description: A fast, beautiful, and distraction-free Gmail client for your terminal.
    binaries:
      - inbox
    repository:
      owner: mattrobenolt
      name: homebrew-stuff
      token: '{{ .Env.HOMEBREW_TAP_TOKEN }}'
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/inbox"]
          end
